### ISSUE TITLE
Authenticate synccouchbase by openid

### ISSUE THREAD

**Issue by zkhahmadi** [RossMerr/IdentityServer4.Couchbase#1]
hi i have a android app and i use identityserver4  for authenticate my users.i am using couchbase as main db in my project and i am using couchbase  syncgatway for syncing my users.I read alot about how can i get sessionid in syncgateway and how can use token got from app for it.but i can implement it and i dont know what is wrong .can you help me?

**Comment by RossMerr** [comment]
Hi @zkhahmadi sorry I can't help with this, I've never used syncgatway and this repository was for a old version of .Net Core when it was still in preview over 4 years ago but it's is no-longer maintained
